
const Chinese={
  "name":"李芊，您好!",
  "PersonalWorkbench":"个人工作台",
  "FileMangement":"公文管理",
  "BussinessOffice":"业务办公",
  "NoticeInfo":"公共信息",
  "Extend":"扩展",
  "Confirm":"确定",
  "Cancel":"取消",
  //个人工作台
  "BacklogWork":"待办工作",
  "ToBeRead":"待阅文件",
  "FinishWork":"已办工作",
  "AttentionFile":"我关注的文件",
  "FoundFile":"我创建的文件",
  "FinishFile":"我已办的文件",
  "ReadFile":"我已阅的文件",
  "DraftFile":"草拟文件",
  "InstitutePost":"学院发文",
  "WorkSettings":"工作设置",
  "PersonalityConfiguration":"个性配置",
  "ChangePassword":"修改密码",
  "SetOut":"外出设置",
  "CommonOpinions":"常用意见",
  "CommonActions":"常用动作",
  "FileType":"文件类型",
  "Sender":"发送人",
  "Sendtime":"发送时间",
  "ProcessingLinks":"处理环节",
  "EmergencyLevel":"紧急程度",
  "FileTitle":"文件标题",

  //文件管理
  "PostManagement":"发文管理",
  "WorkingPost":"在办发文",
  "HavePost":"已办发文",
  "RecordManagement":"收文管理",
  "WorkingAddressee":"在办收文",
  "HaveAddressee":"已办收文",
  "RequestForInstruction":"请示报告",
  "ReportInTheOffice":"在办请示报告",
  "AdvisoryReportMade":"已办请示报告",
  "DepartmentOfPost":"部门发文",
  "OfficeOfOffice":"在办部门发文",
  "DepartmentHasIssuedPost":"已办部门发文",
  "OfficialDocumentForm":"公文登记表",
  "SchoolReadingList":"学院发文一览表",
  "HospitalReadingList":"院内请示报告一览表",
  "DepartmentReadingList":"部门发文一览表",
  "ArchivedFile":"归档文件",
  //业务办公
  "MeetingRoomManagement":"会议室管理",
  "DepartmentalNotice":"部门内部通知",
  "DepartmentalInstructions":"部门内部请示",
  "UnionPost":"工会发文",
  "UnionInstructions":"工会请示",
  "ArchivedFile":"团委发文",
  //公共信息
  "PublicInformation":"公共信息",
  "PeopleOut":"人员外出",
  "InternalBBS":"内部论坛",
  "OrganizationStructure":"组织结构",
  "IESetting":"IE浏览器设置",
  "OAOperationManual":"OA系统操作手册",
  "OAServerUsageInstructions":"OA测试服务器使用说明",
  "MembershipRegistrationDown":"工会会员登记表下载",
  "MessagePlatform":"短信平台",
  "SendMessage":"发送短信",
  "Outbox":"发件箱",
  "Mailbox":"邮箱",
  "Sendmail":"发送邮件",
  "HaveSendmail":"已发邮件",
  "OutRecord":"外出记录",
  "Recipients":"收件人",
  "Title":"主题",
  "MainBody":"正文",
  "Send":"发送",
  "DelayedSend":"发送",
  "SaveDraft":"存草稿",
  "Close":"关闭",
  "Date":"时间",
  "Contacts":"联系人",
  //扩展
  "MySchedule":"我的课表",
  "VideoCommunication":"视频通讯",
  "AddressList":"通讯录",
  "Minutes":"会议记录",
  "MinutesForm":"会议记录表",
  "SystemSettings":"系统设置",
  "StyleAndLanguageSettings":"样式和语言设置",
  "Lesson":"节次",
  "Week":"星期",
  "Monday":"星期一",
  "Tuesday":"星期二",
  "Wednesday":"星期三",
  "Thursday":"星期四",
  "Friday":"星期五",
  "1-2":"第1-2节",
  "3-4":"第3-4节",
  "5-6":"第5-6节",
  "7-8":"第7-8节",
  "9-10":"第9-10节",
  "Opinion":"反馈/意见",
  "LanguageSettings":"语言设置",
  "StyleSettings":"样式设置",
  "File":"文件",
  "Name":"姓名",
  "Matter":"事项",
  "Video":"视频",
  "Videoing":"的视频加载中...",
};
const English={
  "name":"Welcome，Krisy!",
  "PersonalWorkbench":"Personal Workbench",
  "FileMangement":"Document Mangement",
  "BussinessOffice":"Office operations",
  "NoticeInfo":"Public information",
  "Extend":"Extend",
  "Confirm":"Confirm",
  "Cancel":"Cancel",
  //个人工作台
  "BacklogWork":"Backlog Work",
  "ToBeRead":"To Be Read",
  "FinishWork":"Finish Work",
  "AttentionFile":"Attention Document",
  "FoundFile":"Found Document",
  "FinishFile":"Finish Document",
  "ReadFile":"Read Document",
  "DraftFile":"Draft Document",
  "InstitutePost":"College dispatch ",
  "WorkSettings":"Work Settings",
  "PersonalityConfiguration":"Personality Configuration",
  "ChangePassword":"Change Password",
  "SetOut":"SetOut",

  "CommonOpinions":"CommonOpinions",
  "CommonActions":"CommonActions",
  "FileType":"File type",
  "Sender":"Sender",
  "Sendtime":"Send time",
  "ProcessingLinks":"Processing links",
  "EmergencyLevel":"Emergency level",
  "FileTitle":"File title",
  //文件管理
  "PostManagement":"Post Management",
  "WorkingPost":"Working Post",
  "HavePost":"Have Post",
  "RecordManagement":"Record Management",
  "WorkingAddressee":"Working Addressee",
  "HaveAddressee":"Have Addressee",
  "RequestForInstruction":"Request For Instruction",
  "ReportInTheOffice":"Report In The Office",
  "AdvisoryReportMade":"Advisory Report Made",
  "DepartmentOfPost":"Department Of Post",
  "OfficeOfOffice":"Office Of Office",
  "DepartmentHasIssuedPost":"Department Has Issued Post",
  "OfficialDocumentForm":"Official Document Form",
  "SchoolReadingList":"School Reading List",
  "HospitalReadingList":"Hospital Reading List",
  "DepartmentReadingList":"Department Reading List",
  "ArchivedFile":"Archived File",
  //业务办公
  "MeetingRoomManagement":"Meeting Room Management",
  "DepartmentalNotice":"Departmental Notice",
  "DepartmentalInstructions":"Departmental Instructions",
  "UnionPost":"Union Post",
  "UnionInstructions":"Union Instructions",
  "ArchivedFile":"Archived File",
  //公共信息
  "PublicInformation":"Public Information",
  "PeopleOut":"Out worker",
  "InternalBBS":"Internal BBS",
  "OrganizationStructure":"Organization Structure",
  "IESetting":"IE Setting",
  "OAOperationManual":"OAO peration Manual",
  "OAServerUsageInstructions":"OA Server Usage Instructions",
  "MembershipRegistrationDown":"Member ship Registration Down",
  "MessagePlatform":"Message Platform",
  "SendMessage":"Send Message",
  "Outbox":"Outbox",
  "Mailbox":"Mailbox",
  "Sendmail":"Send mail",
  "HaveSendmail":"Have Send mail",
  "OutRecord":"Out Record",
  "Recipients":"Recipients",
  "Title":"Title",
  "MainBody":"Main Body",
  "Send":"Send",
  "DelayedSend":"Delayed Send",
  "SaveDraft":"Save Draft",
  "Close":"Close",
  "Date":"Date",
  "Contacts":"Contacts",
  //扩展
  "MySchedule":"My Schedule",
  "VideoCommunication":"Video Communication",
  "AddressList":"Address List",
  "Minutes":"Meeting minutes",
  "MinutesForm":"Minutes of meetings",
  "SystemSettings":"System Settings",
  "StyleAndLanguageSettings":"Style And Language Settings",
  "Lesson":"Lesson",
  "Week":"Week",
  "Monday":"Monday",
  "Tuesday":"Tuesday",
  "Wednesday":"Wednesday",
  "Thursday":"Thursday",
  "Friday":"Friday",
  "1-2":"1-2",
  "3-4":"3-4",
  "5-6":"5-6",
  "7-8":"7-8",
  "9-10":"9-10",
  "Opinion":"Opinion",
  "LanguageSettings":"Language Settings",
  "StyleSettings":"Style Settings",
  "File":"File",
  "Name":"Name",
  "Matter":"Matter",
  "Video":"Video",
  "Videoing":"\'s video load...",
};

export default {

  namespace: 'example',

  state: {
    language:Chinese,
    languageType:"Chinese",
    styleChange:"light",
    isModal:false,
  },

  reducers: {
    change(state, {payload}){
      if (payload.language === "English"){
        state = {...state ,language:English, languageType:"English"};
      }else {
        state = {...state ,language:Chinese, languageType:"Chinese"};
      }
      return state;
    },
    styleChange(state,{payload}){

      if (payload.style === "light"){
        state = {...state ,styleChange:"light"};
      }else {
        state = {...state ,styleChange:"dark"};
      }
      return state;
    },
    isModalChange(state,{payload}){
      state = {...state ,isModal:payload.isModal};
      console.log(state);
      return state;
    }
  },

  effects: {
    *fetch({ payload }, { call, put }) {  // eslint-disable-line
      yield put({ type: 'save' });
    },
  },

  subscriptions: {
    setup({ dispatch, history }) {  // eslint-disable-line
    },
  },

};
